services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: proyecto_elena
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - proyecto-elena-postgres-data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025" # servidor SMTP falso, aqui apunta la app en dev
      - "8025:8025" # interfaz web para ver los correos recibidos

volumes:
  proyecto-elena-postgres-data:
